name: irohasu_blog
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  appflowy_editor: ^2.3.3
  flutter_bloc: ^8.1.4
  highlight: ^0.7.0
  url_launcher: ^6.2.5
  go_router: ^13.2.2
  equatable: ^2.0.5
  freezed: 2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  bloc: ^8.1.4
  retrofit: ^4.1.0
  dio: ^5.4.2+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_fonts: ^6.2.1
  get_it: ^7.6.8
  collection: ^1.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/